version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3308:3306
    container_name: db_container
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lamp_docker
      - MYSQL_USER=lamp_docker
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    networks:
      - main_network
  php_service:
    image: php:8.1.1-apache
    container_name: php_service
    ports:
      - 9000:80
    depends_on:
      - db
    networks:
      - main_network
  apache_service:
    image: httpd:latest
    container_name: lamp_apache
    ports:
      - 5000:80
    depends_on:
      - php_service
    networks:
      - main_network
networks:
  main_network: